name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.22.9'  # Adjust to your desired Node.js version

      - name: Build
        run: npm run build --if-present

      - name: Debug SSH_PRIVATE_KEY
        run: echo ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Deploy to EC2
        run: |
          chmod 600 ${{ secrets.SSH_PRIVATE_KEY }}
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@35.154.90.106 'cd /test-dev && git pull && npm install && npm start
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

